- Source/ExcelDnaPack/PackProgram.cs
initialize outputDirectory correctly.
> fix for #7

- Source/ExcelDna.Integration/LogDisplay.cs
> Fixes #14 when args array is empty

- Source/ExcelDna.Loader/XlRegistration.cs
Proposed fix for https://github.com/Excel-DNA/ExcelDna/issues/45#issuecomment-154597865
> Fix for issue #45

- Source/ExcelDna.Integration/LogDisplay.Designer.cs
- Source/ExcelDna.Integration/LogDisplay.cs
This changes are required to make Add-ins with the log Section 508 compliant, necessary if you want to sell to the United States government.
http://www.section508.gov/
> Set accessibility properties

- Source/ExcelDnaPack/ResourceHelper.cs
the Endupdate checks now always if 64 Thread are done and after this it checks the next 64 Threads, so it should work fine with large amounts of packages
Signed-off-by: Konrad Mattheis <konrad.mattheis@akquinet.de>
> fix issues #63 for multithreaded packing of more than 64 items

- Source/ExcelDna.Integration/ExcelIntegration.cs
- Source/ExcelDna.Integration/ExcelSynchronizationContext.cs
> Handle error from syncMacro

- Distribution/Samples/Async/AsyncAwaitCS.dna
- Distribution/Samples/Async/AsyncMacros.dna
- Distribution/Samples/Async/ExcelTaskUtilTestCS.dna
- Distribution/Samples/Async/HttpClientVB.vb
- Distribution/Samples/Async/NativeAsyncCancellation.dna
Remove ExcelAsyncUtil obsolete method from samples
> Remove ExcelAsyncUtil obsolete method from samples

- Source/ExcelDna.AddIn.Tasks/Utils/ExcelDnaPhysicalFileSystem.cs
This PR fixes issue with not replacing read-only files in the build output
> Fix #109 Excel-DNA build fails with read-only package

- Source/ExcelDna.Integration/ExcelSynchronizationContext.cs
> Update `COMRunMacro` to use `const` variables for error. Relates to #123

- Distribution/GettingStarted.txt
Seems like RuntimeVersion is case sensitive, should be = "v4.0" not "V4.0"
> Update GettingStarted.txt directions

- Source/ExcelDna.AddIn.Tasks/Utils/ExcelDnaPhysicalFileSystem.cs
> ExcelDnaClean Task: Remove read-only flag in files (if needed) before deleting these files

- Package/ExcelDna.AddIn/tools/install.ps1
- Package/ExcelDna.AddIn/tools/uninstall.ps1
> Remove unused variables in ExcelAddIn Powershell scripts

- Source/ExcelDna.Integration/Excel.cs
- Source/ExcelDna.Integration/ExcelAsyncHandle.cs
- Source/ExcelDna.Integration/ExcelAsyncUtil.cs
- Source/ExcelDna.Integration/ExcelAttributes.cs
- Source/ExcelDna.Integration/ExcelDna.Integration.csproj
- Source/ExcelDna.Integration/ExcelError.cs
- Source/ExcelDna.Integration/ExcelIntegration.cs
- Source/ExcelDna.Integration/ExcelRibbon.cs
- Source/ExcelDna.Integration/MenuManager.cs
- Source/ExcelDna.Integration/Properties/ReSharperAnnotations.cs
- Source/ExcelDna.Integration/XlCall.cs
> Bugfix #156 decorate excel dna with resharper attributes

- Source/ExcelDna.vs2015.sln
> Update ExcelDna solution file to Visual Studio 2017

- Source/ExcelDna.AddIn.Tasks/ExcelDna.AddIn.Tasks.csproj
- Source/ExcelDna.AddIn.Tasks/Utils/DevToolsEnvironment.cs
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/AddInInsideSolutionFolder/AddIn.cs
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/AddInInsideSolutionFolder/AddInInsideSolutionFolder.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/AddInInsideSolutionFolder/MyLibrary-AddIn.dna
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/AddInInsideSolutionFolder/Properties/AssemblyInfo.cs
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget.sln
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/PreAndPostBuildEvents/PreAndPostBuildEvents.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SeparateDnaFilesCustomSuffix_x86_x64/SeparateDnaFilesCustomSuffix_x86_x64.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SeparateDnaFilesDefaultSuffix/SeparateDnaFilesDefaultSuffix.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SharedOutDirProjectOne/SharedOutDirProjectOne.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SharedOutDirProjectTwo/SharedOutDirProjectTwo.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SingleDnaFileAppConfigLinked/AddIn.cs
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SingleDnaFileAppConfigLinked/MyLibrary-AddIn.dna
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SingleDnaFileAppConfigLinked/Properties/AssemblyInfo.cs
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SingleDnaFileAppConfigLinked/SingleDnaFileAppConfigLinked.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SingleDnaFileCustomSuffix_x64/SingleDnaFileCustomSuffix_x64.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SingleDnaFileCustomSuffix_x86/SingleDnaFileCustomSuffix_x86.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SingleDnaFileDefaultSuffix/SingleDnaFileDefaultSuffix.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SingleDnaFileInSubFolderDefaultSuffix/SingleDnaFileInSubFolderDefaultSuffix.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SingleDnaFileNoConfigDefaultSuffix/SingleDnaFileNoConfigDefaultSuffix.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests/ExcelDna.AddIn.Tasks.IntegrationTests.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests/SingleDnaFileAppConfigLinkedIntegrationTests.cs
Fix bug found on #181
ps: This builds on top of #180, so it might look like there's a lot more going on, than it actually is. The _meat_ of this PR is only these two commits below:
* [`2b0b1ad` Update SetDebuggerOptions task to include projects inside solution folders](https://github.com/Excel-DNA/ExcelDna/commit/2b0b1ad7d5643574852bce921059f6a4e92f0e77)
* [`3e76546` Add test for Add-in project inside Solution Folder](https://github.com/Excel-DNA/ExcelDna/commit/3e76546777cc7fc56b47fac1f75426a8fa0a05f4)
> Update `SetDebuggerOptions` to find projects inside Solution Folders

- Source/ExcelDna.AddIn.Tasks/AbstractTask.cs
- Source/ExcelDna.AddIn.Tasks/CleanExcelAddIn.cs
- Source/ExcelDna.AddIn.Tasks/CreateExcelAddIn.cs
- Source/ExcelDna.AddIn.Tasks/ExcelDna.AddIn.Tasks.csproj
- Source/ExcelDna.AddIn.Tasks/Logging/BuildLogger.cs
- Source/ExcelDna.AddIn.Tasks/Logging/IBuildLogger.cs
- Source/ExcelDna.AddIn.Tasks/SetDebuggerOptions.cs
- Source/ExcelDna.AddIn.Tasks/Utils/DevToolsEnvironment.cs
- Source/ExcelDna.AddIn.Tasks/Utils/ExcelDnaProject.cs
- Source/ExcelDna.AddIn.Tasks/Utils/IExcelDnaProject.cs
- Source/ExcelDna.sln.DotSettings
Add some long overdue shared logging infrastructure inside the build tasks, so that all tasks, utilities and friends can participate in the same logging pipeline of the build (which helps me debug and fix #190)
> Better logging infra for build tasks

- Package/ExcelDna.AddIn/build/ExcelDna.AddIn.targets
- Source/ExcelDna.AddIn.Tasks/BuildTaskCommon.cs
- Source/ExcelDna.AddIn.Tasks/CleanExcelAddIn.cs
- Source/ExcelDna.AddIn.Tasks/CreateExcelAddIn.cs
- Source/ExcelDna.AddIn.Tasks/ExcelDna.AddIn.Tasks.csproj
- Source/ExcelDna.AddIn.Tasks/SetDebuggerOptions.cs
- Source/ExcelDna.AddIn.Tasks/Utils/Bitness.cs
- Source/ExcelDna.AddIn.Tasks/Utils/DevToolsEnvironment.cs
- Source/ExcelDna.AddIn.Tasks/Utils/ExcelDetector.cs
- Source/ExcelDna.AddIn.Tasks/Utils/ExcelDnaProject.cs
- Source/ExcelDna.AddIn.Tasks/Utils/IDevToolsEnvironment.cs
- Source/ExcelDna.AddIn.Tasks/Utils/IExcelDetector.cs
- Source/ExcelDna.AddIn.Tasks/Utils/IExcelDnaFileSystem.cs
- Source/ExcelDna.AddIn.Tasks/Utils/IExcelDnaProject.cs
- Source/ExcelDna.AddIn.Tasks/Utils/MessageFilter.cs
- Source/ExcelDna.sln.DotSettings
**NOT YET READY TO MERGE** needs more tests. Putting here just for gathering feedback.
> Fix MSBuild node-reuse issue (WIP)

- Source/ExcelDna.Loader/XlMethodInfo.cs
If the async function throws an exception or an input parameter marshaler fails (e.g. DateTime or bool), the ExcelAsyncHandle is never informed that the function call is finished, keeping Excel calculating.
Fix #230
> Fix conversion wrapper for async functions

- Package/Excel-DNA.Interop/Excel-DNA.Interop.nuspec
> Deprecate NuGet package `Excel-DNA.Interop` replaced by `ExcelDna.Interop`

- Source/ExcelDna.Loader/XlRegistration.cs
The current sort optimization was not helpful if there were characters like "_" as the current sort was case invariant, but not lower case based.
> Fix sort for better perf

- Source/ExcelDna.vs2017.sln
> Update solution to Visual Studio 2019

- README.md
> Add StackOverflow badge for the `excel-dna` tag to README

- Source/ExcelDna.Integration/Excel.cs
When debugging an add-in, check if `ExcelDnaUtil.Application` is being called from a thread that is not the main thread, and throw an exception.
Similar behavior that happens when controls are updated from a non-UI thread in Windows Forms or WPF apps.
Exception is only raised if the add-in is being debugged (i.e. debugger is attached), otherwise behavior continue as is today.
---
Relates to #265, #269, #171
> Check for cross-thread operations accessing COM Application when debugging

- Source/ExcelDna.Integration/Logging.cs
@caioproiete I'm trying out the 'normal' GitHub workflow with a pull request from a branch on a private fork. Can you please check that I'm not doing anything silly (and review the change)?
> Remove LogDisplayTraceListener if configured as Off

- Source/ExcelDna.Integration/ExcelReference.cs
Issue with details - https://github.com/Excel-DNA/ExcelDna/issues/286
> Extend ExcelReference constructor

- Package/ExcelDna.AddIn/build/ExcelDna.AddIn.targets
> Disable ExcelDnaSetDebuggerOptions when building via JetBrains Rider

- Source/ExcelDna.AddIn.Tasks/ExcelDna.AddIn.Tasks.csproj
- Source/ExcelDna.Integration/ExcelDna.Integration.csproj
- Source/ExcelDna.Loader/ExcelDna.Loader.csproj
- Source/ExcelDna/ExcelDna.vcxproj
- Source/ExcelDnaPack/App.config
- Source/ExcelDnaPack/ExcelDnaPack.csproj
- Source/ExcelDnaPack/app.config
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests/ExcelDna.AddIn.Tasks.IntegrationTests.csproj
- C# projects updated to target .NET Framework 4.5
- C++ project updated to use VS2019 build tools (v142)
> Update all projects to target .NET Framework 4.5

- Package/ExcelDna.AddIn/content/ExcelDna-Template.dna
- Source/ExcelDna.Integration/DnaLibrary.cs
- Source/ExcelDna.Integration/DnaLibrarySerialization.cs
- Source/Tests/ExcelDna.IntegrationTests/ExcelDna.IntegrationTests-AddIn.dna
> Update DnaLibrary and DnaTemplate to use 2020/07 xml namespace

- Source/ExcelDnaPack/PackProgram.cs
> Ensure validation errors in ExcelDnaPack fail the build

- Source/ExcelDna.Integration/Excel.cs
As suggested in #376, here a children check to detect the right dialog.
I've managed to test a C++ equivalent method on an old Excel 2003 / Win7 installation, so I presume this solution should be backward compatible.
> Check child window classes to detect the Function Wizard dialog

- .gitignore
- Source/ExcelDna.AddIn.Tasks/ExcelDna.AddIn.Tasks.csproj
- Source/ExcelDna.AddIn.Tasks/Properties/ExcelDna.AddIn.Tasks.targets
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/PreAndPostBuildEvents/PreAndPostBuildEvents.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/ProjectWithNameEndingIn64/App.config
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/ProjectWithNameEndingIn64/ProjectWithNameEndingIn64.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SeparateDnaFilesCustomSuffix_x86_x64/SeparateDnaFilesCustomSuffix_x86_x64.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SeparateDnaFilesDefaultSuffix/App.config
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SeparateDnaFilesDefaultSuffix/SeparateDnaFilesDefaultSuffix.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SharedOutDirProjectOne/SharedOutDirProjectOne.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SharedOutDirProjectTwo/SharedOutDirProjectTwo.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SingleDnaFileAppConfigLinked/SingleDnaFileAppConfigLinked.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SingleDnaFileCustomSuffix_x64/App.config
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SingleDnaFileCustomSuffix_x64/SingleDnaFileCustomSuffix_x64.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SingleDnaFileCustomSuffix_x86/App.config
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SingleDnaFileCustomSuffix_x86/SingleDnaFileCustomSuffix_x86.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SingleDnaFileDefaultSuffix/App.config
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SingleDnaFileDefaultSuffix/SingleDnaFileDefaultSuffix.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SingleDnaFileInSubFolderDefaultSuffix/App.config
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SingleDnaFileInSubFolderDefaultSuffix/SingleDnaFileInSubFolderDefaultSuffix.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SingleDnaFileNoConfigDefaultSuffix/SingleDnaFileNoConfigDefaultSuffix.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests/ExcelDna.AddIn.Tasks.IntegrationTests.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests/IntegrationTestBase.cs
- Source/Tests/ExcelDna.IntegrationTests/ExcelDna.IntegrationTests.csproj
> Update unit tests

- Source/ExcelDna.Host/ExcelDna.Host.vcxproj
- Source/ExcelDna.Host/ExcelDna.Host.vcxproj.filters
- Source/ExcelDna.Host/LPenHelper.cpp
- Source/ExcelDna.Host/LPenHelper.h
- Source/ExcelDna.Host/addin.cpp
- Source/ExcelDna.Host/exports.h
- Source/ExcelDna.Integration/ExcelIntegration.cs
- Source/ExcelDna.Integration/ExcelSynchronizationContext.cs
- Source/ExcelDna.Integration/IIntegrationHost.cs
- Source/ExcelDna.Loader/IntegrationHost.cs
- Source/ExcelDna.Loader/XlAddIn.cs
- Source/ExcelDna/ExcelDna.cpp
- Source/ExcelDna/ExcelDna.h
- Source/ExcelDna/ExcelDna.vcxproj
- Source/ExcelDna/LPenHelper.cpp
- Source/ExcelDna/LPenHelper.h
With the handler for all exceptions.
> Implemented LPenHelper invocation from native code

- Distribution/XmlSchemas/ExcelDna.DnaLibrary.xsd
- Package/ExcelDna.AddIn/build/ExcelDna.AddIn.targets
- Source/ExcelDna.AddIn.Tasks/CreateExcelAddIn.cs
- Source/ExcelDna.Host/dnainfo.cpp
- Source/ExcelDna.Host/dnainfo.h
- Source/ExcelDna.Host/host.cpp
- Source/ExcelDna.ManagedHost/AddInInitialize.cs
- Source/ExcelDna.ManagedHost/ExcelDnaAssemblyLoadContext.cs
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget.sln
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/NET6DisableAssemblyContextUnload/AddIn.cs
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/NET6DisableAssemblyContextUnload/NET6DisableAssemblyContextUnload.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SDKProperties/SDKProperties.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests/NET6DisableAssemblyContextUnloadTests.cs
Usage:
`<DnaLibrary DisableAssemblyContextUnload="true"`
```
<PropertyGroup>
<ExcelAddInDisableAssemblyContextUnload>true</ExcelAddInDisableAssemblyContextUnload>
</PropertyGroup>
```
> Added the flag to set isCollectable to false

- Build/BuildPackages.bat
- MasterBuild/Directory.Build.props
- MasterBuild/Directory.Build.targets
- MasterBuild/MasterBuild.cmd
Edit MasterBuild.cmd header and run it to build ExcelDna and auxiliary packages.
> Created a master build script

- Source/ExcelDna.Host/host.cpp
- Source/ExcelDna.ManagedHost/AssemblyManager.cs
https://groups.google.com/g/exceldna/c/zuKNQu-7q5s
> Fixed .NET 6 add-in reloading error

- Source/ExcelDna.AddIn.Tasks/CreateExcelAddIn.cs
- Source/ExcelDna.PackedResources/ExcelDnaPack.cs
- Source/ExcelDna.PackedResources/ResourceHelper.cs
- Source/ExcelDnaPack/PackProgram.cs
[Govert](https://github.com/Excel-DNA/ExcelDna/pull/519#issuecomment-1298434166) suggested I extend IBuildLogger in to ResourceHelper; done.
> Pass IBuildLogger in to ResourceHelper.ResourceUpdater.

- Source/ExcelDna.Host/host.cpp
> Added detailed error dialog when .NET 6 runtime is not installed

- Build/build.bat
- Package/ExcelDna.AddIn/ExcelDna.AddIn.nuspec
- Package/ExcelDna.AddIn/build/ExcelDna.AddIn.props
- Package/ExcelDna.AddIn/build/ExcelDna.AddIn.targets
- Source/ExcelDna.AddIn.Tasks/CreateExcelAddIn.cs
- Source/ExcelDna.AddIn.Tasks/ExcelDna.AddIn.Tasks.csproj
- Source/ExcelDna.AddIn.Tasks/PackExcelAddIn.cs
- Source/ExcelDna.AddIn.Tasks/Properties/ExcelDna.AddIn.Tasks.targets
- Source/ExcelDna.ManagedHost/AssemblyManager.cs
- Source/ExcelDna.ManagedHost/ExcelDnaAssemblyLoadContext.cs
- Source/ExcelDna.ManagedHost/TempDir.cs
- Source/ExcelDna.PackedResources/ExcelDnaPack.cs
- Source/ExcelDna.PackedResources/ResourceHelper.cs
- Source/ExcelDnaPack/PackProgram.cs
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget.sln
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/NET6PackDeps/AddIn.cs
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/NET6PackDeps/NET6PackDeps.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SDKProperties/SDKProperties.csproj
- Source/Tests/ExcelDna.PackedResourcesTests/ExcelDnaPackTests.cs
1. Increased ExcelDna.AddIn.Tasks project's target framework from net452 to net462.
2. I couldn't find a way to clean the temp directory as there are no unloading events available in ExcelDna.ManagedHost.
> Added packing native libraries from .deps.json and resolving them at runtime

- Build/build.bat
- Package/ExcelDna.Integration/ExcelDna.Integration.nuspec
- Source/ExcelDna.Integration/ExcelAttributes.cs
- Source/ExcelDna.Integration/ExcelDna.Integration.csproj
> Added IntelliSense comments for ExcelDna.Integration into the NuGet package

- README.md
I fixed the broken link to the documentation. 
I am also suggesting adding bullets to improve readability.
> Fix broken documentation link and add bullets
