- Source/ExcelDnaPack/PackProgram.cs
> ExcelDnaPack: Read source item contents as binary instead of assuming UTF-8

- .mailmap
I've just noticed that on commit [519b64](https://github.com/Excel-DNA/ExcelDna/commits?author=cproiete) I had the wrong e-mail address configured on my laptop and it was linking to the wrong GitHub user (`cproiete` instead of `caioproiete`), so I thought I should fix it with a Git `.mailmap`.
Whilst I was at it, I fixed other identities that were incorrect as well, and added the corresponding mappings.
```
$ git shortlog -sne
108  govert_cp <SND\govert_cp>
105  govert_cp <2b25b41bbf01b7d265f78f98bda07e53ff173630NvGJUJxL>
76  Govert van Drimmelen <govert@ic...>
2  Caio Proiete <caio.proiete@gm...>
2  MCLWEB <RNO\_MCLWEB>
2  Paul Harrington <phrrngtn@pa...>
2  Project Collection Service Accounts <vstfs:///Framework/IdentityDomain/a
2  TFSSERVICE <RNO\_TFSSERVICE>
2  [TFS09]\Project …
```
> Add .mailmap to root, to fix committers identities

- Source/ExcelDnaPack/ExcelDnaPack.csproj
- Source/ExcelDnaPack/PackProgram.cs
- Source/ExcelDnaPack/ResourceHelper.cs
if you have big projects the packing can take a long time, for testing if packing is working fine the version without LZMA is much faster (like my project 40sec. -> 3sec.)
There is a new commad line parameter /NC -> this means no compression
Signed-off-by: Konrad Mattheis <konrad.mattheis@akquinet.de>
> * add /NC option (no Compression) for packing without lzma

- Source/ExcelDna.Integration/LogDisplay.cs
It can avoid the NULL exception issue when LogDisplay is configured to be top trace listener. Since it is static, instead of checking the NULL in the function, I create the instance when the class is constructed. So no need NULL check anymore.
> initialize the LogStrings

- Source/ExcelDna.Integration/ComRegistration.cs
The changes here update misbehaving HKCU hive registry references with the following harder references where *SID* is the windows security ID:
HKCU\Software\Classes\\...
become
HKU\\*SID*+"_CLASSES\\"...
and other directories with
HKCU\...
become
HKU\\*SID*\\...
These fixes seem to address issues with misparsing of the HKCU hive.
-Randy
> Fix for "DISP_E_BADINDEX" exception when initializing the Excel Ribbon

- Source/ExcelDnaPack/PackProgram.cs
> ExcelDnaPack: Set Environment.ExitCode to 1 by default (gets set to 0 (zero) when success)

- Source/ExcelDna.Integration/DnaLibrarySerialization.cs
- Source/ExcelDna.Integration/ExternalLibrary.cs
- Source/ExcelDnaPack/PackProgram.cs
- Source/ExcelDnaPack/ResourceHelper.cs
I had a similar problem to this: https://groups.google.com/forum/#!topic/exceldna/HlVeZUZNcqM Basically, I wanted the .xll generated by ExcelDnaPack to have a version number other than the one from the template .xll. VerPatch (linked from that discussion) worked, but actually figuring out how to integrate it into my workflow was tricky. Patching ExcelDnaPack turned out to be easier.
You can now mark ExternalLibrary elements in the .dna file with UseVersionAsOutputVersion="true" to copy their version resource into the output .xll. If you specify this for more than one ExternalLibrary only the first will be used, and a warning will be emitted. If the version copying fails for some reason (like the source file doesn't have it, e.g. if it's a .dna file), then a warning is emitted.
This seemed …
> add facility for copying external library version to xll version

- Package/ExcelDna.AddIn/tools/ExcelDna.AddIn.targets
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget.sln
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/PreAndPostBuildEvents/AddIn.cs
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/PreAndPostBuildEvents/MyLibrary-AddIn.dna
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/PreAndPostBuildEvents/PreAndPostBuildEvents.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/PreAndPostBuildEvents/Properties/AssemblyInfo.cs
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests/ExcelDna.AddIn.Tasks.IntegrationTests.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests/PreAndPostBuildEventsIntegrationTests.cs
Here is a fix for issue #120. Here we're extending the `PostBuild`target, so that our build process runs before the Post-build event, but after the Pre-build event, thus running exactly in the middle, as expected.
i.e. The sequence is what you'd expect:
* **Pre-build event**
* ExcelDna Build
* ExcelDna Pack
* **Post-build event**
I've added an integration test to prove that it works, and to help us catch any regressions to this behavior in the future.
Here is an example output of the integration test:
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.
Running ExcelDna **Pre-build** event
PreAndPostBuildEvents -> C:\dev\caioproiete\ExcelDna\Source\Tests\ExcelDna.AddIn.Tasks.IntegrationTe …
> Make sure ExcelDna build targets run before Post-build event. Fixes #120

- Source/ExcelDna.AddIn.Tasks/Utils/ExcelDnaPhysicalFileSystem.cs
Tiny optimization on `ExcelDnaPhysicalFileSystem` to skip creating a `FileInfo` instance if we're not overriding the file being copied
> ExcelDnaPhysicalFileSystem: Skip FileInfo instance if not overriding the file

- .mailmap
Tiny PR to map @govert's most recent commits. Noticed this when my build server didn't group commits [`c14eb9a`](https://github.com/Excel-DNA/ExcelDna/commit/c14eb9a40db2d0b7eb414c1edc2bc898cb217d69) and [`66e152e`](https://github.com/Excel-DNA/ExcelDna/commit/66e152e0e728dc2227ef9e89a045dbb965a80dcc) when building ExcelDna, as it thinks they were made by different people:
* [`c14eb9a`](https://github.com/Excel-DNA/ExcelDna/commit/c14eb9a40db2d0b7eb414c1edc2bc898cb217d69) - Govert van Drimmelen <govert@****.co.za>
* [`66e152e`](https://github.com/Excel-DNA/ExcelDna/commit/66e152e0e728dc2227ef9e89a045dbb965a80dcc) - Govert <govert@****.co.za>
@govert You might want to fix this moving forward on your machines:
git config --global user.name "Govert van Drimmelen"
git config user.name "Govert …
> Update .mailmap to map to Govert's recent commits

- Source/ExcelDna.AddIn.Tasks/Utils/ExcelDnaPhysicalFileSystem.cs
Pull-request #136 effectively resolves issue #135 by making sure even read-only files can be deleted.
This pull-request improves on that resolution by making sure file attributes are not copied across to the output folder, therefore not creating read-only files in the first place, in case the attributes of the source file have been changed (as per @Rand-Random's reported issue with source control marking files as read-only)
> Update ExcelDnaPhysicalFileSystem.CopyFile to copy files without copying source file attributes

- Package/ExcelDna.AddIn/content/ExcelDna.Build.props
- Package/ExcelDna.AddIn/tools/ExcelDna.AddIn.targets
- Package/ExcelDna.AddIn/tools/install.ps1
- Package/ExcelDna.AddIn/tools/uninstall.ps1
- Source/ExcelDna.AddIn.Tasks/AbstractTask.cs
- Source/ExcelDna.AddIn.Tasks/CleanExcelAddIn.cs
- Source/ExcelDna.AddIn.Tasks/CreateExcelAddIn.cs
- Source/ExcelDna.AddIn.Tasks/ExcelDna.AddIn.Tasks.csproj
- Source/ExcelDna.AddIn.Tasks/SetDebuggerOptions.cs
- Source/ExcelDna.AddIn.Tasks/Utils/Bitness.cs
- Source/ExcelDna.AddIn.Tasks/Utils/DevToolsEnvironment.cs
- Source/ExcelDna.AddIn.Tasks/Utils/ExcelDetector.cs
- Source/ExcelDna.AddIn.Tasks/Utils/ExcelDnaProject.cs
- Source/ExcelDna.AddIn.Tasks/Utils/IExcelDetector.cs
- Source/ExcelDna.AddIn.Tasks/Utils/IExcelDnaProject.cs
- Source/ExcelDna.sln.DotSettings
This PR resolves issues #18 and #19.
The main goal of this PR is to improve the debugging experience of ExcelDna add-ins by automatically detecting the latest Excel version installed on the machine, as well as Excel's bitness (i.e. 32-bit or 64-bit), and set the debugger options in the project where ExcelDna.AddIn is installed, on every build, to the Excel detected, and the right add-in (32 or 64) to be opened with Excel.
This PR allows the following user experiences:
1. **Start debugging an add-in immediately after downloading code from source control**, regardless of the Excel version that the original developer was using, without having to define any setting in the project debug configuration;
2.  **Start debugging an add-in immediately after renaming the `.dna` file**, without having …
> Improve debugging experience / Automatically set debugger options

- Source/ExcelDna.AddIn.Tasks/Utils/ExcelDnaPhysicalFileSystem.cs
Tiny improvement to `ExcelDnaPhysicalFileSystem` to make it for a smoother upgrade from v0.34.6 to vNext.
The new implementation that was merged with PR #139 makes sure that attributes from the source file are not copied to the output folder.
However, there's an edge-case for v0.34.6 users who were affected by the issue PR #139 resolves (i.e. use TFS/Subversion) and they might get an error the first time they try to build the ExcelDna project without doing a full `Rebuild` or `Clean` first, as the output folder will already contain read-only files that need to be overwritten.
> ExcelDnaPhysicalFileSystem.CopyFile: Remove ReadOnly flag if overwriting existing file

- .gitignore
- Distribution/ChangeLog.txt
- Package/ExcelDna.AddIn/ExcelDna.AddIn.nuspec
- Package/ExcelDna.AddIn/build/ExcelDna.AddIn.targets
- Package/ExcelDna.AddIn/tools/install.ps1
- Package/ExcelDna.AddIn/tools/uninstall.ps1
This PR improves the installation process of our `ExcelDna.AddIn` NuGet package by moving the `.targets` file to a `build` folder, [which tells NuGet to (automatically) include the targets file to the project file](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#including-msbuild-props-and-targets-in-a-package) as part of installing the NuGet package.
With that feature, we are able to remove most of the Powershell code that we currently have on `install.ps1` and `uninstall.ps1` to handle just that adding and removing of the `.targets` file.
> Update NuGet package to use `build` feature for adding `.targets` files to projects

- Source/ExcelDna.AddIn.Tasks/ExcelDna.AddIn.Tasks.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget.sln
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/PreAndPostBuildEvents/PreAndPostBuildEvents.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SeparateDnaFilesCustomSuffix_x86_x64/SeparateDnaFilesCustomSuffix_x86_x64.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SeparateDnaFilesDefaultSuffix/SeparateDnaFilesDefaultSuffix.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SharedOutDirProjectOne/SharedOutDirProjectOne.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SharedOutDirProjectTwo/SharedOutDirProjectTwo.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SingleDnaFileAppConfigLinked/AddIn.cs
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SingleDnaFileAppConfigLinked/MyLibrary-AddIn.dna
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SingleDnaFileAppConfigLinked/Properties/AssemblyInfo.cs
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SingleDnaFileAppConfigLinked/SingleDnaFileAppConfigLinked.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SingleDnaFileCustomSuffix_x64/SingleDnaFileCustomSuffix_x64.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SingleDnaFileCustomSuffix_x86/SingleDnaFileCustomSuffix_x86.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SingleDnaFileDefaultSuffix/SingleDnaFileDefaultSuffix.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SingleDnaFileInSubFolderDefaultSuffix/SingleDnaFileInSubFolderDefaultSuffix.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SingleDnaFileNoConfigDefaultSuffix/SingleDnaFileNoConfigDefaultSuffix.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests/ExcelDna.AddIn.Tasks.IntegrationTests.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests/SingleDnaFileAppConfigLinkedIntegrationTests.cs
Add test to validate [Building an Excel DNA addin doesn't find app.config when added to a project as a link #177](https://github.com/Excel-DNA/ExcelDna/issues/177)
> Add test for App.config as linked file

- Source/ExcelDna.AddIn.Tasks/SetDebuggerOptions.cs
> Ask user to restart Visual Studio when `SetDebuggerOptions` fails to run

- Package/Excel-DNA.Lib/Excel-DNA.Lib.nuspec
- Package/Excel-DNA/Excel-DNA.nuspec
- Package/ExcelDna.AddIn/ExcelDna.AddIn.nuspec
- Package/ExcelDna.Integration/ExcelDna.Integration.nuspec
- Package/ExcelDna.XmlSchemas/ExcelDna.XmlSchemas.nuspec
This PR adds the `repository` element to the `.nuspec` files so that a link to this repo is displayed at nuget.org, as per [described in this post](https://blog.nuget.org/20180827/Introducing-Source-Code-Link-for-NuGet-packages.html).
> Add Source Code Link for all NuGet packages

- Source/ExcelDna.Loader/XlParameterInfo.cs
Fix https://github.com/Excel-DNA/ExcelDna/issues/234 , type of the created delegate is then valid for given method directly and also the dynamically created wrappingmethod.
> Fix async UDF with IsExceptionSafe = true

- Source/ExcelDna.Integration/AssemblyLoader.cs
> Update `IExcelAddIn` type scanning to skip abstract classes and interfaces

- Source/ExcelDna.Loader/XlAddIn.cs
Make sure we stop the add-in load process if `ExcelDna.Integration` is loaded from the Global Assembly Cache.
Relates to #223 and #250.
> Detect if ExcelDna.Integration was loaded from the GAC

- Package/ExcelDna.AddIn/build/ExcelDna.AddIn.targets
We've been receiving an increasing number of support requests from users that create projects that use the `PackageReference` style, which is not compatible with Excel-DNA as of this writing (#138).
This PR detects if the Excel-DNA add-in project is using the `PackageReference` style and displays an error message during build, with instructions on how to resolve the issue:
> Excel-DNA is not compatible with projects that use NuGet `PackageReference`. Make sure you create a .NET Framework (Class Library) project and configure Visual Studio to use `packages.config`
The error message above is displayed just before compilation starts, when:
* The user created a `Class Library (.NET Standard)` project (a.k.a. SDK-style project)
* The user created a `Class Library (.NET Framework)` project, but …
> Display error message to user if project is using NuGet PackageReference

- Source/ExcelDna.Integration/Excel.cs
Relates to #265. Allows developers to get access to the `ManagedThreadId` where the Excel-DNA Add-in was loaded from, so they can determine if it's safe to make COM calls or not.
> Expose `ManagedThreadId` of thread where the add-in was loaded

- Package/ExcelDna.AddIn/ExcelDna.AddIn.nuspec
Tiny step towards `PackageReference` support. Tell dotnet publish to not include `ExcelDna.AddIn` as a dependency of the add-in being developed.
---
Relates to #188, #189, #193
> Tell NuGet that `ExcelDna.AddIn` is a DevDependency (for PackageReference compat)

- Source/ExcelDna.Integration/DnaLibrary.cs
- Source/ExcelDna.Integration/Excel.cs
This PR adds a property called `XllPathInfo` to `ExcelDnaUtil` of type `System.IO.FileInfo`. I'm thinking that most of the time, when add-in developers use the property `XllPath`, they are interested in getting the **folder** where the `.xll` is located, in order to access a file that is located on the same folder as the `.xll`.
`XllPathInfo` then becomes an alternative to `XllPath` that also includes a `DirectoryName` property for easy access of the add-in install folder, allowing this:
```csharp
var xllPath = ExcelDnaUtil.XllPath;
var xllFolder = Path.GetDirectoryName(xllPath);
var excelFilePath = Path.Combine(xllFolder, "File.xlsx");
```
To to become this:
```csharp
var excelFilePath = Path.Combine(ExcelDnaUtil.XllPathInfo.DirectoryName, "File.xlsx");
```
---
I'm open to ideas...
- Is …
> Add `XllPathInfo` property to `ExcelDnaUtil`

- Package/ExcelDna.AddIn/build/ExcelDna.AddIn.targets
- Package/ExcelDna.Integration/ExcelDna.Integration.nuspec
- Package/ExcelDna.Integration/tools/install.ps1
Add a build target in the `ExcelDna.AddIn` build process that ensures `ExcelDna.Integration.dll` is **not** copied to the output folder, effectively removing the need for setting `CopyLocal=false` on Excel-DNA Add-in projects.
This also removes the need for the `install.ps1` in the `ExcelDna.Integration` NuGet package.
Resolves #188
> Improve ExcelDna.Integration `CopyLocal=false` story

- Package/ExcelDna.AddIn/build/ExcelDna.AddIn.targets
Change the check for SDK-style project compatibility to a warning instead of an error, with the ability to be suppressed, for devs that can work around the current limitations of SDK-style projects with Excel-DNA.
> Display warning (instead of error) for SDK-style projects

- Package/ExcelDna.AddIn/build/ExcelDna.AddIn.targets
- Package/ExcelDna.AddIn/content/ExcelDna.Build.props
- Add new build parameter `ExcelDnaAllowPackageReferenceProjectStyle` to the `.props` file (defaults to `false`) to allow for displaying error when users install `ExcelDna.AddIn` on projects that use the `PackageReference` style
- Changing the parameter to `true` allows the developer to bypass the error, if the wish to use `PackageReference` with a workaround for copying the files, etc.
> Allow devs to use PackageReference if they wish (despite current limitations)

- Source/ExcelDnaPack/ExcelDnaPack.csproj
I noticed only `Debug` builds had the `PlatformTarget` set to `x86`.
Also setting `Prefer32Bit` to `true` for consistency.
Once we add ExcelDnaPack as a build task, we can add test coverage for x64 and make sure it works as expected.
> Set PlatformTarget to x86 for Release builds & also Prefer32Bit for both Debug and Release

- Distribution/XmlSchemas/ExcelDna.DnaLibrary.xsd
- Distribution/XmlSchemas/ExcelDnaCatalog.xml
- Distribution/XmlSchemas/Readme.md
- Package/ExcelDna.XmlSchemas/ExcelDna.XmlSchemas.nuspec
- RuntimeVersion now only accepts v2.0 in the .dna schema (still valid in the .xll C++ code)
- Bump version of the XSD schema `http://schemas.excel-dna.net/addin/2020/07/dnalibrary`
> Remove v2.0 as an option on the RuntimeVersion attribute of the .dna schema

- Source/ExcelDna.AddIn.Tasks/Utils/ExcelDnaProject.cs
As discussed, this PR ensures that Visual Studio will always open a new `EXCEL.exe` process when the project is run with or without debugging...
> Update SetDebuggerOptions to open Excel in a new process when debugging

- Package/ExcelDna.AddIn/ExcelDna.AddIn.nuspec
`PackageReference` excludes assembly references by default unfortunately, making `developmentDependency` useless for us given that we need the `ExcelDna.Integration` assembly referenced
https://github.com/NuGet/Home/wiki/DevelopmentDependency-support-for-PackageReference
> Remove developmentDependency from ExcelDna.AddIn nuget spec

- Source/ExcelDnaPack/PackProgram.cs
Expand relative paths to absolute paths to avoid issues with calling Windows APIs in some environments (e.g. Azure Pipelines) as reported in https://github.com/Excel-DNA/ExcelDna/issues/311#issuecomment-614449190.
---
Resolves #311
> Use absolute paths when packing files in ExcelDnaPack

- Build/build.bat
- Package/ExcelDna.AddIn/ExcelDna.AddIn.nuspec
- Package/ExcelDna.AddIn/build/ExcelDna.AddIn.targets
- Source/ExcelDna.AddIn.Tasks/ExcelDna.AddIn.Tasks.csproj
Projects that use ExcelDna.Addin can be built with dotnet core 5.0 on windows directly through ```dotnet build```, so thereby not requiring Visual Studio to be installed.
Multi-target Addin.Tasks for net472 and net5.0-windows.
Adds a new variable ExcelDnaTasksPath to the Excel.Addin.Targets to redirect to the correct Excel.Addin.Tasks.dll during build.
It's my first PR on ExcelDna - so consider this a draft PR...
> Addin.Task is compatible with net5.0-windows

- Package/ExcelDna.AddIn/content/ExcelDna.Build.props
My first pull request ever. Hope this goes well :-)
I've had some trouble with virus scanners since around october 2021. Read some stories about an increase of xlls spreading virusses as well, so they might have had to become more stringent.
I've had success disabling the compression feature of ExcelDnaPack. The scanner, in this case Thor Agent from Heimdal security, does not block my xll anymore.
This change makes the possibility of disabling compression more visible. Hope it helps somebody.
> Optionally disable ExcelDnaPack compression

- Package/ExcelDna.AddIn/ExcelDna.AddIn.nuspec
- Package/ExcelDna.AddIn/build/ExcelDna.AddIn.props
- Package/ExcelDna.AddIn/build/ExcelDna.AddIn.targets
- Source/ExcelDna.AddIn.Tasks/ExcelDna.AddIn.Tasks.csproj
When 'ExcelDna.AddIn' package is referenced:
* Set 'EnableDynamicLoading' to true if it is not set to false in the project file.
* Set 'ProduceReferenceAssembly' to false if it is not set to true in the project file.
* Give a build error if the target framework is 'net6.0' and not 'net6.0-windows' or some specific '-windows' version.
> EnableDynamicLoading and other project settings

- Source/ExcelDna.ManagedHost/AddInInitialize.cs
- Source/ExcelDna.ManagedHost/AssemblyManager.cs
- Source/ExcelDna.ManagedHost/ExcelDnaAssemblyLoadContext.cs
There are a lot of log entries like this when the code JIT-compiles:
ExcelDna.Integration Warning: 1 : Assembly SYSTEM.DRAWING.COMMON could not be loaded from resources.
The AssemblyLoadContext.Load(AssemblyName) method provides the first chance for the AssemblyLoadContext to resolve, load, and return the assembly. Not loading an assembly from local resources is fine here and we should not log warnings.
> Disabled spurious assembly load warnings in .NET 6

- Source/ExcelDna.PackedResources/ExcelDnaPack.cs
- Source/ExcelDna.PackedResources/ResourceHelper.cs
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget.sln
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/FrameworksPack/AddIn.cs
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/FrameworksPack/FrameworksPack.csproj
> `<TargetFrameworks>net472;net6.0-windows</TargetFrameworks>`
> 
> First TFM builds OK, then second one fails:
> 
> 1>  Target ExcelDnaPack:
> 1>    ExcelDnaPack: bin\Debug\net6.0-windows\TestNuNuGet-AddIn.dna -> bin\Debug\net6.0-windows\TestNuNuGet-AddIn-packed.xll
> 1>    PackExcelAddIn: Running PackExcelAddIn Task
> 1>    MSBUILD : PackExcelAddIn error DNA126955310: The operation completed successfully
> 1>    MSBUILD : PackExcelAddIn error DNA126955310: System.ComponentModel.Win32Exception (0x80004005): The operation completed successfully
> 1>    MSBUILD : PackExcelAddIn error DNA126955310:    at ResourceHelper.ResourceUpdater..ctor(String fileName)
> 1>    MSBUILD : PackExcelAddIn error DNA126955310:    at ExcelDna.PackedResources.ExcelDnaPack.Pack(String dnaPath, String …
> Fixed a pack error on build

- Source/ExcelDna.AddIn.Tasks/Properties/ExcelDna.AddIn.Tasks.targets
- Source/ExcelDna.PackedResources/ExcelDnaPack.cs
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget.sln
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/FrameworksUseVersionAsOutputVersion/AddIn.cs
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/FrameworksUseVersionAsOutputVersion/FrameworksUseVersionAsOutputVersion-AddIn.dna
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/FrameworksUseVersionAsOutputVersion/FrameworksUseVersionAsOutputVersion.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/NET6DisableAssemblyContextUnload/NET6DisableAssemblyContextUnload.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/NET6LaunchSettings/NET6LaunchSettings.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/NET6LaunchSettingsDisabled/NET6LaunchSettingsDisabled.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/NET6LaunchSettingsVB/NET6LaunchSettingsVB.vbproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/NET6Minimal/NET6Minimal.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/NET6Sign/NET6Sign.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/NET6Unpack/NET6Unpack.csproj
When targeting multiple frameworks and using UseVersionAsOutputVersion="true":
> 1>MSBUILD : PackExcelAddIn error DNA731704007:   ~~> ERROR: Error copying version to output version: The system cannot find the file specified
> 1>MSBUILD : PackExcelAddIn error DNA731704007: System.InvalidOperationException:   ~~> ERROR: Error copying version to output version: The system cannot find the file specified
> 1>MSBUILD : PackExcelAddIn error DNA731704007:    at ExcelDna.PackedResources.ExcelDnaPack.PackDnaLibrary(Byte[] dnaContent, String dnaDirectory, ResourceUpdater ru, Boolean compress, Boolean multithreading) in e:\programming\Govert\ExcelDna\Source\ExcelDna.PackedResources\ExcelDnaPack.cs:line 197
> 1>MSBUILD : PackExcelAddIn error DNA731704007:    at …
> Fixed Error copying version to output version

- Source/ExcelDna.AddIn.Tasks/CleanExcelAddIn.cs
- Source/ExcelDna.AddIn.Tasks/CreateExcelAddIn.cs
- Source/ExcelDna.AddIn.Tasks/ExcelDebugTask.cs
- Source/ExcelDna.AddIn.Tasks/PackExcelAddIn.cs
- Source/ExcelDna.AddIn.Tasks/SetDebuggerOptions.cs
- Source/ExcelDna.AddIn.Tasks/Utils/DevToolsEnvironment.cs
- Source/ExcelDna.AddIn.Tasks/Utils/ExcelDetector.cs
- Source/ExcelDna.AddIn.Tasks/Utils/ExcelDnaProject.cs
- Source/ExcelDna.AddIn.Tasks/Utils/ProcessRunner.cs
- Source/ExcelDna.AddIn.Tasks/Utils/SignTool.cs
- Source/ExcelDna.PackedResources/ExcelDna.PackedResources.projitems
- Source/ExcelDna.PackedResources/ExcelDnaPack.cs
- Source/ExcelDna.PackedResources/Logging/IBuildLogger.cs
- Source/ExcelDna.PackedResources/Logging/MessageImportance.cs
- Source/ExcelDnaPack/ConsoleLogger.cs
- Source/ExcelDnaPack/PackProgram.cs
- Source/Tests/ExcelDna.PackedResourcesTests/ExcelDna.PackedResourcesTests.csproj
- Source/Tests/ExcelDna.PackedResourcesTests/ExcelDnaPackTests.cs
Add build logging to help service #518 
Inject IBuildLogger to ExcelDnaPack.Pack and use it to log to the standard Build output instead of the console. ConsoleLogger added an implementation of the same for PackProgram.
Decoupled IBuildLogger from implementation and pull down to PackedResources so it can be reused, but kept the implementation unmoved from Addin.Tasks.Logging.
> LogPackDna#518

- MasterBuild/MasterBuild.cmd
- Source/ExcelDna.sln
Minor oversight I think on your part; caused me issues because I wasn't getting the MsBuild prefix at all, and with more than one version of VS on the box the sln was defaulting to open with VS instead.
Adding the SolutionItems to the sln was just a convenience, hope it's ok for you. MasterBuild.cmd is the important one.
> Fix missing param sent to additional usages of BuildPackages.bat

- Source/Templates/Projects/CSfull/.template.config/template.json
- Source/Templates/Projects/CSfunction/.template.config/template.json
- Source/Templates/Projects/FSfull/.template.config/template.json
- Source/Templates/Projects/FSfunction/.template.config/template.json
- Source/Templates/Projects/VBfull/.template.config/template.json
- Source/Templates/Projects/VBfunction/.template.config/template.json
Before:
After:
Now it works with .NET 7 and doesn't require -lang for C#.
> Added templates grouping

- Package/ExcelDna.AddIn/build/ExcelDna.AddIn.props
- Package/ExcelDna.AddIn/build/ExcelDna.AddIn.targets
- Source/ExcelDna.AddIn.Tasks/CreateExcelAddIn.cs
- Source/ExcelDna.AddIn.Tasks/PackExcelAddIn.cs
- Source/ExcelDna.PackedResources/ExcelDnaPack.cs
- Source/ExcelDna.PackedResources/ResourceHelper.cs
- Source/ExcelDnaPack/PackProgram.cs
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/NET6PackDeps/NET6PackDeps.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SDKProperties/SDKProperties.csproj
- Source/Tests/ExcelDna.PackedResourcesTests/ExcelDnaPackTests.cs
1. The build task logs which files we are including according to the .deps.json information as Source:
>   PackExcelAddIn:   ->  Updating resource: Type: DNA, Name: __MAIN__, Length: 555
>   PackExcelAddIn:   ->  Updating resource: Type: ASSEMBLY_LZMA, Name: NET6PACKDEPS, Length: 2523
>   PackExcelAddIn:   ->  Updating resource: Type: ASSEMBLY_LZMA, Name: SYSTEM.MANAGEMENT, Source: Managed deps.json, Length: 83824
>   PackExcelAddIn:   ->  Updating resource: Type: ASSEMBLY_LZMA, Name: SYSTEM.DATA.SQLITE, Source: Managed deps.json, Length: 119610
>   PackExcelAddIn:   ->  Updating resource: Type: NATIVE_LIBRARY_LZMA, Name: SQLITE.INTEROP.DLL, Source: Native deps.json, Length: 765473
2. A managed dependency with a Runtime ID overrides a dependency without one. E.g. "win …
> Implemented packing managed assemblies from deps.json

- Build/BuildPackages.bat
- Build/build.bat
- MasterBuild/Directory.Build.props
- Package/ExcelDna.Integration/ExcelDna.Integration.nuspec
- Package/package.cmd
1. I can't locally test how it works (without pushing to NuGet servers) -  VS doesn't support local .snupkg.
2. ExcelDna.Integration.1.6.1-beta2.snupkg with .pdb files is now additionally created in the nupkg directory. See [Publishing a symbol package](https://learn.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg#publishing-a-symbol-package) for publishing.
> Added Source Link support for ExcelDna.Integration package

- Source/ExcelDna.PackedResources/ExcelDnaPack.cs
- Source/ExcelDnaPack/PackProgram.cs
Add the '/x64' command line option to ExcelDnaPack to select the correct generic ExcelDna.xll without renaming it.
> Add '/x64' option to ExcelDnaPack

- Source/ExcelDna.Host/host.cpp
- Source/ExcelDna.Loader/XlAddIn.cs
1. Added a descriptive message for FrameworkMissingFailure error.
2. Replaced more assert messages in ExcelDna.Host with traditional message box errors including error codes.
3. Fixed XlAutoOpen error message display.
4. Changed required .NET runtime to v6.0.2.
> Startup reliability

- Source/ExcelDna.Loader/XlRegistration.cs
Added cleanup for allocated delegate handles.
> Fixed reloading .NET 6 add-in with ExplicitRegistration

- Package/ExcelDna.AddIn/build/ExcelDna.AddIn.targets
- Source/ExcelDna.AddIn.Tasks/CreateExcelAddIn.cs
- Source/ExcelDna.AddIn.Tasks/PackExcelAddIn.cs
- Source/ExcelDna.Loader/DocUtil.cs
- Source/ExcelDna.Loader/XlAddIn.cs
- Source/ExcelDna.Loader/XlMethodInfo.cs
- Source/ExcelDna.ManagedHost/AddInInitialize.cs
- Source/ExcelDna.ManagedHost/AssemblyManager.cs
- Source/ExcelDna.PackedResources/ExcelDnaPack.cs
- Source/ExcelDna.PackedResources/ResourceHelper.cs
- Source/ExcelDnaPack/PackProgram.cs
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget.sln
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SDKPackDoc/Functions.cs
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests.TestTarget/SDKPackDoc/SDKPackDoc.csproj
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests/SDKPackDocTests.cs
- Source/Tests/ExcelDna.AddIn.Tasks.IntegrationTests/SDKPublishDocTests.cs
- Source/Tests/ExcelDna.PackedResourcesTests/ExcelDnaPackTests.cs
A .chm help file is now stored as a resource in the published .xll, instead of being copied to the publish folder.
Extraction of a help file to a temp dir and getting the right path into the help topic is implemented in Loader.
For .NET Core add-ins, ExcelDna.Host temp dir is reused for help file extraction on add-in loading. It is automatically deleted on ExcelDna.Host temp dir cleanup.
For .NET Framework add-ins, ExcelDna.Loader temp dir is created for help file extraction. No cleanup occurs. (We don’t have ExcelDna.Host temp dir in this configuration and I could not find an alternative solution.) Can be prevented by manually distributing .chm along with .xll - if a help file is present in the same directory with .xll, it is used directly and no extraction occurs.
> Implemented packing a .chm help file

- Package/ExcelDna.AddIn/build/ExcelDna.AddIn.targets
Currently checks for TargetFrameworkVersion.Substring(1,1) >= 6 which fails with net10.0. Not sure if the test is .net core vs framework or actually requires .net6.0 or higher. Have updated to using TargetFramework instead of TargetFrameworkVersion. Have implemented very simple .Substring(0,3) == 'net' or not.
> Update ExcelDna.AddIn.targets for .net10

- Source/ExcelDna.Integration/AssemblyLoader.cs
- Source/ExcelDna.Integration/DnaLibrary.cs
- Source/ExcelDna.Integration/ExcelAttributes.cs
- Source/ExcelDna.Integration/ExtendedRegistration/Registration.cs
- Source/ExcelDna.Integration/Registration/AsyncRegistration.cs
- Source/ExcelDna.Integration/Registration/ExcelRegistration.cs
- Source/Tests/ExcelDna.AddIn.RuntimeTests/AddIn.cs
- Source/Tests/ExcelDna.AddIn.RuntimeTests/DynamicFunctions.cs
- Source/Tests/ExcelDna.AddIn.RuntimeTests/MapArrayFunctionRegistration.cs
- Source/Tests/ExcelDna.RuntimeTests/Registration.cs
Additionally fixed repetitive async function registration processing and compilation warnings.
> Added extended registration transformations pipeline for explicit/dynamic functions
